Shop/apps/products/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path('<int:product_id>/', views.detail, name='detail')
]

Shop/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include(('products.urls','products'), namespace='products')),
              ]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/apps/products/models.py
from django.db import models

class Product(models.Model):
    product_name = models.CharField("Название", max_length=200)
    product_type = models.CharField("Категория", max_length=200)
    product_prices = models.DecimalField("Цена", max_digits=10, decimal_places=2)
    product_img1 = models.ImageField('Фотография товара 1', upload_to='img', default="Null")
    product_img2 = models.ImageField('Фотография товара 2', upload_to='img', blank=True, default="Null")
    product_info = models.TextField('Описание товара')
    delivery_date = models.DateField('Ближайший срок доставки')

    def __str__(self):
        return self.product_name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

Shop/apps/products/views.py
from django.shortcuts import render
from django.http import HttpResponse
from.models import Product
# Create your views here.

app_name = 'products'
def index(request):
    return HttpResponse("Я работаю!")

def index(request):
    new_product = Product.objects.order_by('product_name')[:10]
    return render(request, 'products/list.html', {'product': new_product})

def detail(request, product_id):
    try:
        product = Product.objects.get(id=product_id)
    except Exception:
        return HttpResponse('SDSFSDFDSF SDFSDFSDFSDFSD FSDFSDF')
    return render(request, 'products/product.html', {'product': product})

def img(request):
    num_img = Product.objects.all().count()
    return render(request, 'products/list.html', context={'num_img': num_img})

Shop/apps/products/templates/products/list.html
{% extends 'main.html' %}
{% load static %}

{% block title %}
    <h1>Страничка с товарами</h1>
{% endblock %}


{% block content %}
    <h2>Каталог товаров</h2>
    {% if product %}
        {% for product in product %}
            <div class="test">
                <img src='{{product.product_img1.url}}' alt="{{product_img1}}" class="row"  ><br>
                <a href="{% url 'products:detail' product.id %}" class="row" >{{product.product_name}}</a><br>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}

Shop/apps/products/templates/products/product.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
    <img src='{{product.product_img1.url}}' class="list">
    <p class="listinfo">{{product.product_prices}} руб</p>
    <h3 class="listinfo">{{ product.product_name }}</h3>
    <p class="listinfo">{{product.product_info}}</p>
{% endblock %}

Shop/templates/main.html
{% load static %}
<html lang="ru">
<head>
    <link href="{% static 'products/css/stylesheet.css' %}" rel="stylesheet" type="text/css" >
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" >
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" rel="stylesheet" >
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

</head>


<body>

    <aside>
        <h5 class="menu">Меню</h5>
        <h5 class="menu">Меню3</h5>
        <h5 class="menu">Меню2</h5>
        <h5 class="menu">Меню1</h5>

    </aside>

    <main>
        <h1>Сама страница сайта</h1>
        {% block content %}{% endblock %}
    </main>

    <footer>
        <h1>Подвал сайта</h1>
    </footer>
</body>
</html>